name: Deploy Tibco BW to Docker Desktop

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t tibcotestapp .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Deploy to Docker Desktop
      run: docker run -d -p 32001:32001 tibcotestapp:latest
